/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotationRouteImport } from './routes/quotation'
import { Route as NewcustomerRouteImport } from './routes/newcustomer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const QuotationRoute = QuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const NewcustomerRoute = NewcustomerRouteImport.update({
  id: '/newcustomer',
  path: '/newcustomer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/newcustomer': typeof NewcustomerRoute
  '/quotation': typeof QuotationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/newcustomer': typeof NewcustomerRoute
  '/quotation': typeof QuotationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/newcustomer': typeof NewcustomerRoute
  '/quotation': typeof QuotationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/newcustomer' | '/quotation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/newcustomer' | '/quotation'
  id: '__root__' | '/' | '/about' | '/newcustomer' | '/quotation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NewcustomerRoute: typeof NewcustomerRoute
  QuotationRoute: typeof QuotationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quotation': {
      id: '/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof QuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newcustomer': {
      id: '/newcustomer'
      path: '/newcustomer'
      fullPath: '/newcustomer'
      preLoaderRoute: typeof NewcustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NewcustomerRoute: NewcustomerRoute,
  QuotationRoute: QuotationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
